# Generated by Django 5.2.17 on 2026-09-09 16:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_review_product_seller_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WishlistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wished_by', to='products.product', verbose_name='Mahsulot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Istak',
                'verbose_name_plural': 'Istaklar',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='products_wi_user_id_8088b2_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'product'), name='one_wish_per_user_product')],
            },
        ),
    ]
