# Generated by Django 5.2.17 on 2026-09-05 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('orders', '0002_pickuppoint_order_courier_order_delivery_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pickup_point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff', to='orders.pickuppoint', verbose_name='Punkt'),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('customer', 'Xaridor'), ('courier', 'Kuryer'), ('pickup', 'Punkt xodimi'), ('admin', 'Admin')], default='customer', max_length=10, verbose_name='Rol'),
        ),
    ]
