# Generated by Django 5.2.17 on 2026-09-05 09:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_pickup_point_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('customer', 'Xaridor'), ('seller', 'Sotuvchi'), ('courier', 'Kuryer'), ('pickup', 'Punkt xodimi'), ('admin', 'Admin')], default='customer', max_length=10, verbose_name='Rol'),
        ),
        migrations.CreateModel(
            name='RoleApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('seller', 'Sotuvchi'), ('courier', 'Kuryer'), ('pickup', 'Punkt xodimi')], max_length=10, verbose_name="So'ralgan rol")),
                ('full_name', models.CharField(max_length=150, verbose_name="To'liq ism")),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon')),
                ('address', models.TextField(verbose_name='Aniq manzil')),
                ('passport', models.CharField(blank=True, max_length=30, verbose_name='Passport (seriya + raqam)')),
                ('card_number_masked', models.CharField(max_length=24, verbose_name='Karta (maskalangan)')),
                ('card_last4', models.CharField(max_length=4, verbose_name='Karta oxirgi 4')),
                ('point_name', models.CharField(blank=True, max_length=150, verbose_name='Punkt nomi')),
                ('point_address', models.TextField(blank=True, verbose_name='Punkt manzili')),
                ('point_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Punkt kengligi')),
                ('point_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Punkt uzunligi')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('approved', 'Qabul qilingan'), ('rejected', 'Rad etilgan')], default='pending', max_length=10, verbose_name='Holat')),
                ('note', models.TextField(blank=True, verbose_name='Admin izohi')),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL, verbose_name="Ko'rib chiqqan")),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_applications', to=settings.AUTH_USER_MODEL, verbose_name='Arizachi')),
            ],
            options={
                'verbose_name': 'Rol arizasi',
                'verbose_name_plural': 'Rol arizalari',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='accounts_ro_user_id_e44c8e_idx'), models.Index(fields=['role', 'status'], name='accounts_ro_role_e37f5a_idx')],
            },
        ),
    ]
