# Generated by Django 5.2.17 on 2026-09-05 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_role_roleapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='roleapplication',
            name='address_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Manzil kengligi'),
        ),
        migrations.AddField(
            model_name='roleapplication',
            name='address_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Manzil uzunligi'),
        ),
    ]
