# Generated by Django 5.2.17 on 2026-09-09 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_roleapplication_address_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Avatar'),
        ),
        migrations.AddField(
            model_name='user',
            name='roles',
            field=models.JSONField(blank=True, default=list, help_text='Rol kodlari ro\'yxati: ["seller", "courier"]', verbose_name="Qo'shimcha rollar"),
        ),
    ]
