# Generated by Django 5.2.17 on 2026-09-05 07:12

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message="Kod faqat lotin harflari (A-Z), raqamlar, tire va pastki chiziqdan iborat bo'lishi kerak (4–50 belgi).", regex='^[A-Z0-9_-]{4,50}$')], verbose_name='Kod')),
                ('percent', models.PositiveSmallIntegerField(help_text="1–90% oralig'ida.", validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(90)], verbose_name='Chegirma %')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Tavsif (xabar matni)')),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Boshlanish vaqti')),
                ('valid_to', models.DateTimeField(verbose_name='Tugash vaqti')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('max_uses', models.PositiveIntegerField(blank=True, help_text="Bo'sh bo'lsa — cheklanmagan.", null=True, verbose_name='Maksimal foydalanish soni')),
                ('used_count', models.PositiveIntegerField(default=0, verbose_name='Ishlatilgan soni')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Yaratgan admin')),
            ],
            options={
                'verbose_name': 'Chegirma kupon',
                'verbose_name_plural': 'Chegirma kuponlari',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['code'], name='discounts_c_code_3b6115_idx'), models.Index(fields=['valid_to', 'is_active'], name='discounts_c_valid_t_52c903_idx')],
            },
        ),
    ]
